### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by surbhitkapoor** [Maluuba/qgen-workshop#4]
This is the error which I got after running the command to prepare the data
**PYTHONPATH=".:$PYTHONPATH" python qgen/data.py**

Error:
Traceback (most recent call last):
  File "qgen/data.py", line 249, in <module>
    trim_embeddings()
  File "qgen/data.py", line 227, in trim_embeddings
    for data in [_load_training_stories().values(), _load_test_stories().values()]:
  File "qgen/data.py", line 208, in _load_training_stories
    _training_stories = _read_data("train.csv")
  File "qgen/data.py", line 160, in _read_data
    document_text = row[1]
IndexError: list index out of range

**Comment by vivekangadi1** [comment]
question_text = row[2]
    169             question_words = _tokenize(question_text)
    170 

IndexError: list index out of range

**Comment by mady143** [comment]
Hi @surbhitkapoor ,
This is the error which I got after running the command to prepare the data
PYTHONPATH=".:$PYTHONPATH" python qgen/data.py

Error:
Traceback (most recent call last):
File "qgen/data.py", line 249, in
trim_embeddings()
File "qgen/data.py", line 227, in trim_embeddings
for data in [_load_training_stories().values(), _load_test_stories().values()]:
File "qgen/data.py", line 208, in _load_training_stories
_training_stories = _read_data("train.csv")
File "qgen/data.py", line 160, in _read_data
document_text = row[1]
IndexError: list index out of range
getting same issue can you  please help me to resolve this issue

Thanks & Regards,
Manikantha Sekhar..
